import type { LocationConfig } from '../types';

/**
 * Texas State Parks, State Natural Areas, and State Historic Sites
 * managed by the Texas Parks & Wildlife Department.
 *
 * Coordinates are [longitude, latitude] as required by react-simple-maps.
 */
export const TEXAS_STATE_PARKS: LocationConfig[] = [
  // === State Parks ===
  { id: 'abilene-sp', name: 'Abilene State Park', coordinates: [-99.883, 32.233] },
  { id: 'atlanta-sp', name: 'Atlanta State Park', coordinates: [-94.144, 33.160] },
  { id: 'balmorhea-sp', name: 'Balmorhea State Park', coordinates: [-103.784, 30.948] },
  { id: 'bastrop-sp', name: 'Bastrop State Park', coordinates: [-97.288, 30.108] },
  { id: 'bentsen-rgv-sp', name: 'Bentsen-Rio Grande Valley State Park', coordinates: [-98.382, 26.173] },
  { id: 'big-bend-ranch-sp', name: 'Big Bend Ranch State Park', coordinates: [-103.950, 29.470] },
  { id: 'big-spring-sp', name: 'Big Spring State Park', coordinates: [-101.492, 32.234] },
  { id: 'blanco-sp', name: 'Blanco State Park', coordinates: [-98.421, 30.095] },
  { id: 'bonham-sp', name: 'Bonham State Park', coordinates: [-96.154, 33.621] },
  { id: 'brazos-bend-sp', name: 'Brazos Bend State Park', coordinates: [-95.610, 29.370] },
  { id: 'buescher-sp', name: 'Buescher State Park', coordinates: [-97.162, 30.045] },
  { id: 'caddo-lake-sp', name: 'Caddo Lake State Park', coordinates: [-94.174, 32.683] },
  { id: 'caprock-canyons-sp', name: 'Caprock Canyons State Park & Trailway', coordinates: [-101.061, 34.385] },
  { id: 'cedar-hill-sp', name: 'Cedar Hill State Park', coordinates: [-96.960, 32.610] },
  { id: 'choke-canyon-sp', name: 'Choke Canyon State Park', coordinates: [-98.350, 28.490] },
  { id: 'cleburne-sp', name: 'Cleburne State Park', coordinates: [-97.553, 32.258] },
  { id: 'colorado-bend-sp', name: 'Colorado Bend State Park', coordinates: [-98.443, 31.035] },
  { id: 'cooper-lake-sp', name: 'Cooper Lake State Park', coordinates: [-95.694, 33.366] },
  { id: 'copper-breaks-sp', name: 'Copper Breaks State Park', coordinates: [-99.740, 34.110] },
  { id: 'daingerfield-sp', name: 'Daingerfield State Park', coordinates: [-94.725, 33.033] },
  { id: 'davis-mountains-sp', name: 'Davis Mountains State Park', coordinates: [-103.931, 30.595] },
  { id: 'dinosaur-valley-sp', name: 'Dinosaur Valley State Park', coordinates: [-97.813, 32.251] },
  { id: 'eisenhower-sp', name: 'Eisenhower State Park', coordinates: [-96.638, 33.811] },
  { id: 'estero-llano-grande-sp', name: 'Estero Llano Grande State Park', coordinates: [-97.947, 26.129] },
  { id: 'falcon-sp', name: 'Falcon State Park', coordinates: [-99.140, 26.570] },
  { id: 'fort-boggy-sp', name: 'Fort Boggy State Park', coordinates: [-95.988, 31.170] },
  { id: 'fort-parker-sp', name: 'Fort Parker State Park', coordinates: [-96.527, 31.598] },
  { id: 'fort-richardson-sp', name: 'Fort Richardson State Park & Historic Site', coordinates: [-98.408, 33.217] },
  { id: 'franklin-mountains-sp', name: 'Franklin Mountains State Park', coordinates: [-106.530, 31.912] },
  { id: 'galveston-island-sp', name: 'Galveston Island State Park', coordinates: [-94.927, 29.200] },
  { id: 'garner-sp', name: 'Garner State Park', coordinates: [-99.741, 29.581] },
  { id: 'goliad-sp', name: 'Goliad State Park & Historic Site', coordinates: [-97.387, 28.653] },
  { id: 'goose-island-sp', name: 'Goose Island State Park', coordinates: [-96.989, 28.132] },
  { id: 'guadalupe-river-sp', name: 'Guadalupe River State Park', coordinates: [-98.500, 29.868] },
  { id: 'hueco-tanks-sp', name: 'Hueco Tanks State Park & Historic Site', coordinates: [-106.041, 31.918] },
  { id: 'huntsville-sp', name: 'Huntsville State Park', coordinates: [-95.528, 30.622] },
  { id: 'inks-lake-sp', name: 'Inks Lake State Park', coordinates: [-98.370, 30.729] },
  { id: 'kickapoo-cavern-sp', name: 'Kickapoo Cavern State Park', coordinates: [-100.470, 29.610] },
  { id: 'lake-bob-sandlin-sp', name: 'Lake Bob Sandlin State Park', coordinates: [-95.021, 33.059] },
  { id: 'lake-brownwood-sp', name: 'Lake Brownwood State Park', coordinates: [-99.010, 31.828] },
  { id: 'lake-casa-blanca-sp', name: 'Lake Casa Blanca International State Park', coordinates: [-99.431, 27.540] },
  { id: 'lake-colorado-city-sp', name: 'Lake Colorado City State Park', coordinates: [-100.882, 32.327] },
  { id: 'lake-corpus-christi-sp', name: 'Lake Corpus Christi State Park', coordinates: [-97.873, 28.072] },
  { id: 'lake-livingston-sp', name: 'Lake Livingston State Park', coordinates: [-95.005, 30.652] },
  { id: 'lake-mineral-wells-sp', name: 'Lake Mineral Wells State Park & Trailway', coordinates: [-98.046, 32.812] },
  { id: 'lake-somerville-sp', name: 'Lake Somerville State Park & Trailway', coordinates: [-96.718, 30.332] },
  { id: 'lake-tawakoni-sp', name: 'Lake Tawakoni State Park', coordinates: [-95.955, 32.892] },
  { id: 'lake-whitney-sp', name: 'Lake Whitney State Park', coordinates: [-97.367, 31.898] },
  { id: 'lockhart-sp', name: 'Lockhart State Park', coordinates: [-97.710, 29.847] },
  { id: 'longhorn-cavern-sp', name: 'Longhorn Cavern State Park', coordinates: [-98.356, 30.692] },
  { id: 'lbj-sp', name: 'Lyndon B. Johnson State Park & Historic Site', coordinates: [-98.623, 30.247] },
  { id: 'martin-creek-lake-sp', name: 'Martin Creek Lake State Park', coordinates: [-94.566, 32.254] },
  { id: 'martin-dies-jr-sp', name: 'Martin Dies Jr. State Park', coordinates: [-94.158, 30.548] },
  { id: 'mckinney-falls-sp', name: 'McKinney Falls State Park', coordinates: [-97.722, 30.183] },
  { id: 'meridian-sp', name: 'Meridian State Park', coordinates: [-97.692, 31.920] },
  { id: 'mission-tejas-sp', name: 'Mission Tejas State Park', coordinates: [-95.168, 31.545] },
  { id: 'monahans-sandhills-sp', name: 'Monahans Sandhills State Park', coordinates: [-102.813, 31.610] },
  { id: 'mother-neff-sp', name: 'Mother Neff State Park', coordinates: [-97.467, 31.347] },
  { id: 'mustang-island-sp', name: 'Mustang Island State Park', coordinates: [-97.160, 27.673] },
  { id: 'old-tunnel-sp', name: 'Old Tunnel State Park', coordinates: [-98.600, 29.972] },
  { id: 'palmetto-sp', name: 'Palmetto State Park', coordinates: [-97.587, 29.589] },
  { id: 'palo-duro-canyon-sp', name: 'Palo Duro Canyon State Park', coordinates: [-101.661, 34.939] },
  { id: 'pedernales-falls-sp', name: 'Pedernales Falls State Park', coordinates: [-98.258, 30.308] },
  { id: 'possum-kingdom-sp', name: 'Possum Kingdom State Park', coordinates: [-98.532, 32.867] },
  { id: 'purtis-creek-sp', name: 'Purtis Creek State Park', coordinates: [-96.002, 32.350] },
  { id: 'ray-roberts-lake-sp', name: 'Ray Roberts Lake State Park', coordinates: [-96.997, 33.375] },
  { id: 'resaca-de-la-palma-sp', name: 'Resaca de la Palma State Park', coordinates: [-97.593, 26.120] },
  { id: 'san-angelo-sp', name: 'San Angelo State Park', coordinates: [-100.509, 31.455] },
  { id: 'sea-rim-sp', name: 'Sea Rim State Park', coordinates: [-94.048, 29.680] },
  { id: 'seminole-canyon-sp', name: 'Seminole Canyon State Park & Historic Site', coordinates: [-101.317, 29.692] },
  { id: 'sheldon-lake-sp', name: 'Sheldon Lake State Park', coordinates: [-95.157, 29.862] },
  { id: 'south-llano-river-sp', name: 'South Llano River State Park', coordinates: [-99.812, 30.442] },
  { id: 'stephen-f-austin-sp', name: 'Stephen F. Austin State Park', coordinates: [-96.098, 29.927] },
  { id: 'tyler-sp', name: 'Tyler State Park', coordinates: [-95.287, 32.472] },
  { id: 'village-creek-sp', name: 'Village Creek State Park', coordinates: [-94.170, 30.253] },

  // === State Natural Areas ===
  { id: 'devils-river-sna', name: 'Devils River State Natural Area', coordinates: [-100.983, 29.900] },
  { id: 'enchanted-rock-sna', name: 'Enchanted Rock State Natural Area', coordinates: [-98.820, 30.506] },
  { id: 'government-canyon-sna', name: 'Government Canyon State Natural Area', coordinates: [-98.760, 29.550] },
  { id: 'hill-country-sna', name: 'Hill Country State Natural Area', coordinates: [-99.183, 29.637] },
  { id: 'honey-creek-sna', name: 'Honey Creek State Natural Area', coordinates: [-98.483, 29.883] },
  { id: 'lost-maples-sna', name: 'Lost Maples State Natural Area', coordinates: [-99.572, 29.808] },

  // === State Historic Sites (with outdoor recreation) ===
  { id: 'fort-griffin-shs', name: 'Fort Griffin State Historic Site', coordinates: [-99.225, 32.934] },
  { id: 'fort-lancaster-shs', name: 'Fort Lancaster State Historic Site', coordinates: [-101.660, 30.661] },
  { id: 'fort-leaton-shs', name: 'Fort Leaton State Historic Site', coordinates: [-104.048, 29.456] },
  { id: 'fort-mckavett-shs', name: 'Fort McKavett State Historic Site', coordinates: [-100.106, 30.828] },
  { id: 'monument-hill-shs', name: 'Monument Hill & Kreische Brewery State Historic Sites', coordinates: [-96.897, 29.868] },
  { id: 'san-jacinto-shs', name: 'San Jacinto Battleground State Historic Site', coordinates: [-95.080, 29.750] },
  { id: 'washington-on-brazos-shs', name: 'Washington-on-the-Brazos State Historic Site', coordinates: [-96.148, 30.330] },
  { id: 'fanthorp-inn-shs', name: 'Fanthorp Inn State Historic Site', coordinates: [-96.401, 30.631] },
];
